---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Build
description: Represents a build.
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of build
    readOnly: true
    format: uuid
    type:
    - string

  identity:
    anyOf:
    - "$ref": "/schemata/build#/definitions/id"

  url:
    description: a link to the build
    example: "https://semaphoreci.com/api/internal/renderedtext/semaphore/build{/id}"
    readOnly: true
    type:
      - string

  threads_url:
    description: a link to build's threads
    example: "https://semaphoreci.com/api/internal/renderedtext/semaphore/builds/{build_id}/threads"
    readOnly: true
    type:
      - string

  branch_url:
    description: a link to build's branch
    example: "https://semaphoreci.com/api/internal/renderedtext/semaphore/branches/{branch_id}"
    readOnly: true
    type:
      - string

  status:
    description: status of the build
    readOnly: true
    example: "queued"
    type:
      - string
    enum:
      - queued
      - running
      - finished

  result:
    description: Type of a thread
    readOnly: true
    example: "failed"
    type:
      - string
    enum:
      - failed
      - passed
      - stopped
      - canceled

  created_at:
    description: when build was created
    format: date-time
    type:
    - string

  updated_at:
    description: when build was updated
    format: date-time
    type:
    - string

  started_at:
    description: when build was started
    format: date-time
    type:
    - string

  finished_at:
    description: when build was finished
    format: date-time
    type:
    - string

links:
- description: Create a new build.
  href: "/{(%2Fschemata%2Fowner%23%2Fdefinitions%2Fidentity)}/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}/builds"
  method: POST
  rel: create
  schema:
    properties: {}
    type:
    - object
  title: Create

- description: Info for existing build.
  href: "/{(%2Fschemata%2Fowner%23%2Fdefinitions%2Fidentity)}/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}/builds/{(%2Fschemata%2Fbuild%23%2Fdefinitions%2Fidentity)}"
  method: GET
  rel: self
  title: Info

- description: List existing builds.
  href: "/builds"
  method: GET
  rel: instances
  title: List

properties:
  created_at:
    "$ref": "/schemata/build#/definitions/created_at"
  id:
    "$ref": "/schemata/build#/definitions/id"
  url:
    "$ref": "/schemata/build#/definitions/url"
  status:
    "$ref": "/schemata/build#/definitions/status"
  result:
    "$ref": "/schemata/build#/definitions/result"
  created_at:
    "$ref": "/schemata/build#/definitions/created_at"
  started_at:
    "$ref": "/schemata/build#/definitions/started_at"
  finished_at:
    "$ref": "/schemata/build#/definitions/finished_at"
  updated_at:
    "$ref": "/schemata/build#/definitions/updated_at"
  threads_url:
    "$ref": "/schemata/build#/definitions/threads_url"
  branch_url:
    "$ref": "/schemata/build#/definitions/branch_url"

id: schemata/build
