---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Project
description: ""
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of project
    readOnly: true
    example: 7
    type:
    - integer
  name:
    description: name of project
    readOnly: true
    example: Semaphore
    type:
    - string
  identity:
    anyOf:
    - "$ref": "/schemata/project#/definitions/id"
  created_at:
    description: when project was created
    format: date-time
    type:
    - string
  updated_at:
    description: when project was updated
    format: date-time
    type:
    - string

links:
- description: Create a new project.
  href: "/teams/{(%2Fschemata%2Fteam%23%2Fdefinitions%2Fidentity)}/projects"
  method: POST
  rel: create
  schema:
    properties:
      name:
        "$ref": "/schemata/project#/definitions/name"
    required:
      - name
    type:
    - object
  title: Create
- description: Delete an existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: DELETE
  rel: destroy
  title: Delete
- description: Info for existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: GET
  rel: self
  title: Info
- description: List projects belonging to the team.
  href: "/team/{(%2Fschemata%2Fteam%23%2Fdefinitions%2Fidentity)}/projects"
  method: GET
  rel: instances
  title: \- List by Team
- description: List all projects belonging to the user.
  href: "/user/user_id/projects"
  method: GET
  rel: instances
  title: \- List by User
- description: Update an existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: PATCH
  rel: update
  schema:
    properties:
      name:
        "$ref": "/schemata/project#/definitions/name"
    required:
      - name
    type:
    - object
  title: Update

properties:
  created_at:
    "$ref": "/schemata/project#/definitions/created_at"
  id:
    "$ref": "/schemata/project#/definitions/id"
  name:
    "$ref": "/schemata/project#/definitions/name"
  updated_at:
    "$ref": "/schemata/project#/definitions/updated_at"
id: schemata/project
