---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Shared Configuration
description: Contains environment variables and configuration files consumed by multiple projects.
stability: prototype
strictProperties: true
type:
- object

definitions:
  id:
    description: unique identifier of shared configuration
    readOnly: true
    format: uuid
    type:
    - string
  name:
    description: name of shared configuration
    readOnly: true
    example: ECS prod
    type:
    - string
  description:
    description: shared configuration description
    readOnly: true
    example: AWS keys for deployment to ECS prod environment
    type:
    - string
  identity:
    anyOf:
    - "$ref": "/schemata/shared_configuration#/definitions/id"
  created_at:
    description: when shared configuration was created
    format: date-time
    type:
    - string
  updated_at:
    description: when shared configuration was updated
    format: date-time
    type:
    - string

links:
- description: Create a new shared configuration.
  href: "/shared_configurations"
  method: POST
  rel: create
  schema:
    properties: 
      name: 
        "$ref": "/schemata/shared_configuration#/definitions/name"
      description:
        "$ref": "/schemata/shared_configuration#/definitions/description"
    required:
    - name
    type:
    - object
  title: Create
- description: Delete an existing shared configuration.
  href: "/shared_configurations/{(%2Fschemata%2Fshared_configuration%23%2Fdefinitions%2Fidentity)}"
  method: DELETE
  rel: destroy
  schema:
    properties: 
      name: 
        "$ref": "/schemata/shared_configuration#/definitions/id"
    required:
    - name
    type:
    - object
  title: Delete
- description: Info for existing shared configuration.
  href: "/shared_configurations/{(%2Fschemata%2Fshared_configuration%23%2Fdefinitions%2Fidentity)}"
  method: GET
  rel: self
  schema:
    properties: 
      name: 
        "$ref": "/schemata/shared_configuration#/definitions/id"
    required:
    - name
    type:
    - object
  title: Info
- description: List existing shared configurations.
  href: "/shared_configurations"
  method: GET
  rel: instances
  title: List
- description: Update an existing shared configuration.
  href: "/shared_configurations/{(%2Fschemata%2Fshared_configuration%23%2Fdefinitions%2Fidentity)}"
  method: PATCH
  rel: update
  schema:
    properties: 
      name: 
        "$ref": "/schemata/shared_configuration#/definitions/name"
      description:
        "$ref": "/schemata/shared_configuration#/definitions/description"
    type:
    - object
  title: Update
- description: Add shared configuration to the team. [Responce is incorrect (201 with shared configuration object). I think appropriate would be 204.]
  href: "/teams/{(%2Fschemata%2Fteam%23%2Fdefinitions%2Fidentity)}/shared_configurations/{(%2Fschemata%2Fshared_configuration%23%2Fdefinitions%2Fidentity)}"
  method: POST
  rel: link
  title: \- Link to the Team
- description: Remove shared configuration from the team. [Same comment as for add SC to the team.]
  href: "/teams/{(%2Fschemata%2Fteam%23%2Fdefinitions%2Fidentity)}/shared_configurations/{(%2Fschemata%2Fshared_configuration%23%2Fdefinitions%2Fidentity)}"
  method: DELETE
  rel: unlink
  title: \- Unlink from the Team

properties:
  created_at:
    "$ref": "/schemata/shared_configuration#/definitions/created_at"
  id:
    "$ref": "/schemata/shared_configuration#/definitions/id"
  name:
    "$ref": "/schemata/shared_configuration#/definitions/name"
  description:
    "$ref": "/schemata/shared_configuration#/definitions/description"
  updated_at:
    "$ref": "/schemata/shared_configuration#/definitions/updated_at"
id: schemata/shared_configuration
